config/routes.rb
MiApp::Application.routes.draw do
  get "usuario_tipos/txt"

  resources :menu_usuario_tipos

  resources :usuarios

  resources :menus

  resources :usuario_tipos

  resources :comentarios

  get "home/index"

  get "home/acerca_de"

  get "home/cambio_clave"

  get "home/ingreso"

  get "home/cambio_clave"

  get "home/acceso_denegado"

  get "home/salir"

  post "home/ingresar"

  post "home/cambiar_clave"

  root :to => 'home#index'

end

app/models/usuario_tipo.rb
class UsuarioTipo < ActiveRecord::Base

    before_destroy :validates_no_dependents

    validates_uniqueness_of :nombre, :message => 'existe en la base de datos'
    validates_presence_of   :nombre, :message => 'no puede estar vacio'

    # Tipo de relacion
    has_many :usuarios #, :dependent => :destroy Si se usa esto, eliminar un tipo de usuario, elimina los usuarios
    has_and_belongs_to_many :menus, :join_table => 'menu_usuario_tipos'

    # -------------------- Procedimientos de las validaciones ----------------------

    def validates_no_dependents
        if (self.usuarios.count() > 0) or (self.menus.count() > 0)
            errors.add :base, 'El Registro tiene Usuarios/Menu asociados'
            false
        end
    end # Fin validates_no_dependents

end

app/controllers/usuario_tipos_controller.rb
class UsuarioTiposController < ApplicationController

  include UsuarioTiposHelper

  before_filter :access_menu

  def index
    @usuario_tipos = UsuarioTipo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @usuario_tipos }
      format.xml { render :xml => @usuario_tipos }
    end
  end

  def show
    @usuario_tipo = UsuarioTipo.find(params[:id])
  end

  def new
    @usuario_tipo = UsuarioTipo.new
  end

  def create
    @usuario_tipo = UsuarioTipo.new(params[:usuario_tipo])

    if @usuario_tipo.save
      render action: "show", :notice => 'Registro creado.'
    else
      render action: "new"
    end
  end

  def edit
    @usuario_tipo = UsuarioTipo.find(params[:id])
  end

  def update
    @usuario_tipo = UsuarioTipo.find(params[:id])

    if @usuario_tipo.update_attributes(params[:usuario_tipo])
      render action: "show", :notice => 'Registro actualizado.'
    else
      render action: "edit"
    end
  end

  def destroy
    @usuario_tipo = UsuarioTipo.find(params[:id])
    @usuario_tipo.destroy
    redirect_to usuario_tipos_url
  end

  # Genera TXT con los datos de la tabla
  def txt
    generar_planilla_tipo_usuarios
    send_file 'public/archivo.xls', :type => 'application/vnd.ms-excel', :disposition => 'inline'
  end

end

app/helpers/usuario_tipos_helper.rb
module UsuarioTiposHelper

    include FechasHelper

    def generar_planilla_tipo_usuarios
        # Crear el libro
        workbook = Spreadsheet::Excel.new('public/archivo.xls')
        format = Spreadsheet::Format.new :color => :blue, :weight => :bold, :size => 10

        # Crear las hojas
        worksheet1 = workbook.add_worksheet('Tipo Usuarios')
        #worksheet2 = workbook.add_worksheet('Hoja2')

        # Escribir en las hojas especificando las celdas.
        worksheet1.write(0, 0, ['ID', 'Nombre', 'Creado', 'Actualizado'], format)

        registros = UsuarioTipo.find(:all, :order => 'id')
        linea = 0
        registros.each do |registro|
            linea = linea + 1
            worksheet1.write(linea, 0, [registro.id, registro.nombre, ver_fecha_df(registro.created_at), ver_fecha_df(registro.updated_at)])
        end

        # Se cierra el libro
        workbook.close
    end # Fin generar_planilla_tipo_usuarios

end

app/views/usuario_tipos/_form.html.erb
<%= form_for(@usuario_tipo) do |f| %>

  <% if @usuario_tipo.errors.any? %>
  <div>
      <h3> <%= image_tag('error.gif') %> El registro no se puede guardar:
      </h3>
      
      <ul>
        <% @usuario_tipo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  </div>
  <% end %>

  <pre>
  <%= f.label 'Nombre:' %> <%= f.text_field :nombre %></pre>

  <%= f.submit 'Guardar' %> <br /> <br />

<% end %>

app/views/usuario_tipos/edit.html.erb
<h2>Editar Tipo de Usuario</h2>

<%= render 'form' %>

<%= link_to image_tag('volver.gif'), usuario_tipos_path %>

app/views/usuario_tipos/index.html.erb
<h2><%= link_to image_tag('tipos.png') %> Listado de Tipos de Usuario</h2>

<table class='webgrid'>
  <tr class='webgrid-header'>
	<th>ID</th>
    <th>Nombre</th>
    <th>Creado</th>
	<th>Modificado</th>
    <th></th>
    <th></th>
  </tr>

<% @usuario_tipos.each do |registro| %>
  <tr class='webgrid-row-style'>
	<td><%= registro.id %></td>
    <td><%= registro.nombre %></td>
	<td><%= ver_fecha_df(registro.created_at) %></td>
    <td><%= ver_fecha_df(registro.updated_at) %></td>
    <td><%= link_to image_tag('edit.gif'),   edit_usuario_tipo_path(registro) %></td>
    <td><%= link_to image_tag('delete.gif'), registro, confirm: 'Esta Seguro?', method: :delete %></td>
  </tr>
<% end %>
</table>

<%= link_to image_tag('crear.gif'), new_usuario_tipo_path %>
<%= link_to image_tag('save.gif'), usuario_tipos_txt_path %>

app/views/usuario_tipos/new.html.erb
<h2>Nuevo Tipo de Usuario</h2>

<%= render 'form' %>

<%= link_to image_tag('volver.gif'), usuario_tipos_path %>

app/views/usuario_tipos/show.html.erb
<h3 id="notice">
	<%= image_tag('ok.gif') %>
	<%= notice %>
</h3>

<p>
	<b>Nombre:</b>
	<%= @usuario_tipo.nombre %>
</p>

<%= link_to image_tag('volver.gif'), usuario_tipos_path %>