config/routes.rb
MiApp::Application.routes.draw do
  get "usuario_tipos/txt"

  resources :menu_usuario_tipos

  resources :usuarios

  resources :menus

  resources :usuario_tipos

  resources :comentarios

  get "home/index"

  get "home/acerca_de"

  get "home/cambio_clave"

  get "home/ingreso"

  get "home/cambio_clave"

  get "home/acceso_denegado"

  get "home/salir"

  post "home/ingresar"

  post "home/cambiar_clave"

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :login_required, :only => [:acerca_de, :salir, :cambio_clave]

  def index
  end

  def acerca_de
  end

  # GET ingreso
  def ingreso
  end

  # POST ingreso
  def ingresar
    login = params[:datos][:login]
    clave = params[:datos][:clave]
    existe = Usuario.find_by_login_and_clave(login, clave)

    if !existe
      session[:usuario] = nil
      session[:userid] = nil
      redirect_to home_ingreso_path, :notice => 'Usuario/Clave incorrectos'
    else
      session[:usuario] = existe.login + '(' + existe.nombre + ')'
      session[:userid] = existe.id
      redirect_to home_index_path
    end
  end

  # GET cambio_clave
  def cambio_clave
  end

  # POST cambio_clave
  def cambiar_clave
    clave_act = params[:datos][:clave_act]
    clave_new = params[:datos][:clave_new]
    clave_rep = params[:datos][:clave_rep]

    usuario = Usuario.find(session[:userid])

    if (usuario.clave != clave_act) or (clave_new != clave_rep)
      redirect_to home_cambio_clave_path, :notice => 'Error en clave actual o claves no coinciden'
    else
      usuario.clave = clave_new
      if usuario.update_attributes(usuario.attributes)
        redirect_to home_cambio_clave_path, :notice => 'Clave cambiada con exito'
      else
        redirect_to home_cambio_clave_path, :notice => usuario.errors.full_messages.first
      end
    end
  end

  def acceso_denegado
  end

  def salir
    reset_session
    redirect_to home_index_path
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/acceso_denegado.html.erb
<h2 align='center'>
	No tiene Acceso a esta Pagina <br />
	<%= image_tag('llaveno.png') %>
</h2>

<pre align='center'>
Comuniquese con el administrador del sistema, esta funcionalidad no puede ser accedida por el usuario actual.
Tampoco esta permitido el acceso si no es usuario de la aplicacion.
</pre>

app/views/home/acerca_de.html.erb
<h2 align='center'>Control de Acceso a Usuarios</h2>

<h3 align='center'>
  Aplicacion - Version 1.0 - Desarrollado en Ruby on Rails <br /> <br />
  <%= image_tag('rails.png') %>
</h3>

<p align='center'>
Visitenos en BLA BLA BLA
</p>

app/views/home/cambio_clave.html.erb
<h2> <%= image_tag('llave.png') %> Cambiar Clave</h2>

<%= form_for :datos, :url => { :action => 'cambiar_clave' } do |f| %>

  <h4> <%= notice %> </h4>

  <pre>
  <%= f.label 'Clave Actual:' %> <%= f.password_field :clave_act %>
  <%= f.label 'Clave Nueva: ' %> <%= f.password_field :clave_new %>
  <%= f.label 'Repita Clave:' %> <%= f.password_field :clave_rep %></pre>

  <%= f.submit 'Actualizar' %> <br /> <br />

<% end %>

<%= link_to image_tag('volver.gif'), home_index_path %>

app/views/home/index.html.erb
<h2>Opciones de Menu y Acceso a Usuarios</h2>

<table>
  <tr>
	<td> <%= link_to image_tag('tipos.png'), usuario_tipos_path %> </td>
    <td></td>
    <td> <%= link_to image_tag('usuario.png'), usuarios_path %> </td>
    <td></td>
    <td> <%= link_to image_tag('menu.png'), menus_path %> </td>
    <td></td>
    <td> <%= link_to image_tag('control.png'), menu_usuario_tipos_path %> </td>
  </tr>

  <tr>
	<th>Tipos de Usuarios</th>
    <th></th>
    <th>Usuarios del Sistema</th>
    <th></th>
    <th>Opciones de Menu</th>
    <th></th>
    <th>Control de Acceso</th>
  </tr>
</table>

<p>
Cree sus propios menu, agrege usuarios al sistema y ademas controle el
acceso de los usuarios a cada una de las opciones creadas.
Los botones de la barra superior son para el mantenimiento de la aplicacion.
Saludos!!
</p>

app/views/home/ingreso.html.erb
<h2> <%= image_tag('llave.png') %> Ingreso al Sistema</h2>

<%= form_for :datos, :url => { :action => 'ingresar' } do |f| %>

  <h4> <%= notice %> </h4>

  <pre>
  <%= f.label 'User ID:' %> <%= f.text_field :login %>
  <%= f.label 'Clave:  ' %> <%= f.password_field :clave %></pre>

  <%= f.submit 'Ingresar' %> <br /> <br />

<% end %>

<%= link_to image_tag('volver.gif'), home_index_path %>