config/routes.rb
MiApp::Application.routes.draw do
  get "usuario_tipos/txt"

  resources :menu_usuario_tipos

  resources :usuarios

  resources :menus

  resources :usuario_tipos

  resources :comentarios

  get "home/index"

  get "home/acerca_de"

  get "home/cambio_clave"

  get "home/ingreso"

  get "home/cambio_clave"

  get "home/acceso_denegado"

  get "home/salir"

  post "home/ingresar"

  post "home/cambiar_clave"

  root :to => 'home#index'

end

app/models/menu_usuario_tipo.rb
class MenuUsuarioTipo < ActiveRecord::Base

  validates_uniqueness_of :menu_id, :scope => :usuario_tipo_id, :message => ' con ese tipo usuario ya existe en la base de datos'

  # Relacion con tablas
  belongs_to :menu
  belongs_to :usuario_tipo
  
end

app/controllers/menu_usuario_tipos_controller.rb
class MenuUsuarioTiposController < ApplicationController

  before_filter :access_menu

  def index
    @menu_usuario_tipos = MenuUsuarioTipo.all
  end

  def show
    @menu_usuario_tipo = MenuUsuarioTipo.find(params[:id])
  end

  def new
    @menu_usuario_tipo = MenuUsuarioTipo.new
  end

  def create
    @menu_usuario_tipo = MenuUsuarioTipo.new(params[:menu_usuario_tipo])

    if @menu_usuario_tipo.save
      render action: "show", notice: 'Registro creado.'
    else
      render action: "new"
    end
  end

  def edit
    @menu_usuario_tipo = MenuUsuarioTipo.find(params[:id])
  end

  def update
    @menu_usuario_tipo = MenuUsuarioTipo.find(params[:id])

    if @menu_usuario_tipo.update_attributes(params[:menu_usuario_tipo])
      render action: "show", notice: 'Registro actualizado.'
    else
      render action: "new"
    end
  end

  def destroy
    @menu_usuario_tipo = MenuUsuarioTipo.find(params[:id])
    @menu_usuario_tipo.destroy
    redirect_to menu_usuario_tipos_url
  end

end

app/helpers/menu_usuario_tipos_helper.rb
module MenuUsuarioTiposHelper

	include FechasHelper
    
	# Con un objeto de tipo MenuUsuarioTipo, arma el item del menu
	def mostrar_item(menu)

		# Si el item tiene url, controlador o accion, arma link, sino solo label
		if (menu.controller != '') or (menu.action != '') or (menu.url != '')
			if menu.url != ''
				link_to menu.nombre, menu.url
			else
				link_to menu.nombre, :controller => menu.controller, :action => menu.action
			end
		else
			menu.nombre
		end

	end # Fin mostrar_item

	def mostrar_item_img(menu)
		icono = 'icono_menu.gif'
		icono = menu.icono if  menu.icono != ''
		image_tag(icono) if menu.orden != 0
	end # Fin mostrar_item_img

	# Carga el menu dinamico de la aplicacion
	def cargar_menu
		if session[:usuario]
			@opciones = Menu.find(:all, :order => 'padre, orden')
		else
			@opciones = []
		end
	end # Fin Carga el menu dinamico de la aplicacion

end

app/views/menu_usuario_tipos/_form.html.erb
<%= form_for(@menu_usuario_tipo) do |f| %>

  <% if @menu_usuario_tipo.errors.any? %>
  <div>
      <h3> <%= image_tag('error.gif') %> El registro no se puede guardar:
      </h3>
      
      <ul>
        <% @menu_usuario_tipo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  </div>
  <% end %>

  <pre>
  <%= f.label 'Menu:     ' %> <%= f.collection_select(:menu_id, Menu.all, :id, :nombre) %>
  <%= f.label 'Tipo Usr: ' %> <%= f.collection_select(:usuario_tipo_id, UsuarioTipo.all, :id, :nombre) %></pre>

  <%= f.submit 'Guardar' %> <br /> <br />

<% end %>

app/views/menu_usuario_tipos/edit.html.erb
<h2>Editar Acceso</h2>

<%= render 'form' %>

<%= link_to image_tag('volver.gif'), menu_usuario_tipos_path %>

app/views/menu_usuario_tipos/index.html.erb
<h2><%= link_to image_tag('control.png') %> Accesos</h2>

<table class='webgrid'>
  <tr class='webgrid-header'>
    <th>Menu</th>
    <th>Tipo Usuario</th>
    <th>Creado</th>
    <th>Modificado</th>
    <th></th>
    <th></th>
  </tr>

<% @menu_usuario_tipos.each do |registro| %>
  <tr class='webgrid-row-style'>
	<td><%= registro.menu.nombre %></td>
	<td><%= registro.usuario_tipo.nombre %></td>
    <td><%= ver_fecha_df(registro.updated_at) %></td>
    <td><%= ver_fecha_df(registro.created_at) %></td>
    <td><%= link_to image_tag('edit.gif'),   edit_menu_usuario_tipo_path(registro) %></td>
    <td><%= link_to image_tag('delete.gif'), registro, confirm: 'Esta Seguro?', method: :delete %></td>
  </tr>
<% end %>
</table>

<%= link_to image_tag('crear.gif'), new_menu_usuario_tipo_path %>

app/views/menu_usuario_tipos/new.html.erb
<h2>Nuevo Acceso</h2>

<%= render 'form' %>

<%= link_to image_tag('volver.gif'), menu_usuario_tipos_path %>

app/views/menu_usuario_tipos/show.html.erb
<h3>
	<%= image_tag('ok.gif') %>
	<%= notice %>
</h3>

<p>
	<b>Acceso:</b>
	<%= @menu_usuario_tipo.menu.nombre + ' - ' + @menu_usuario_tipo.usuario_tipo.nombre %>
</p>

<%= link_to image_tag('volver.gif'), menu_usuario_tipos_path %>